
library(tidyverse)
#Install cesdata2
#devtools::install_github("sjkiss/cesdata2")
library(cesdata2)

#Seprate ces79 and ces80 to two separate files
ces7980 %>%
  #This variable indicates Rs who completed the 1979 survey, no panel respondents
  filter(V4002==1)->ces79

ces7980 %>%
  #This variable indicates Rs who completed the 1980 survey, may also havecompleted the 1979 survey; a user should check.
  filter(V4008==1)->ces80
# Drop the `election` variable from ces80
# This is a quirk of the election80 variable;
# I'll explain another time. Trust me; it is necessary and in this order.
ces80 %>%
  select(-election)->ces80
#Remove the '80' from the duplicate ces80 variables
# in the ces780
names(ces80)<-str_remove_all(names(ces80), "80")
#Check
#tail(names(ces80))

### Decide On CES 1993 sample
# this command includes only those respondents that completed the 1993 Campaign and Post-Election Survey
# ces93[!is.na(ces93$RTYPE4), ] -> ces93

#Use Panel Respondents for 2004
ces0411 %>%
  filter(str_detect(ces0411$survey, "PES04"))->ces04

# Use Panel Respondets for 2006
ces0411 %>%
  filter(str_detect(ces0411$survey, "PES06"))->ces06
# Use Panel Respondents for 2008
ces0411 %>%
  filter(str_detect(ces0411$survey, "PES08"))->ces08

#Use Panel respondents for 2011
ces0411 %>%
  filter(str_detect(ces0411$survey, "PES11"))->ces11

#Rename variables in 2004
#Strip out any instance of `04` in the names of 04
names(ces04)<-str_remove_all(names(ces04), "04")

#Rename variables in 2006
#Strip out any instance of `06` in the names of 06
names(ces06)<-str_remove_all(names(ces06), "06")
#Rename variables in 2008
#Strip out any instance of `08` in the names of 08
names(ces08)<-str_remove_all(names(ces08), "08")

#Rename variables in 2011
#Strip out any instance of `11` in the names of 11
names(ces11)<-str_remove_all(names(ces11), "11")

# List data frames
ces.list<-list(ces65, ces68, ces72_nov, ces74, ces79, ces80, ces84, ces88, ces93, ces97, ces00, ces04, ces06, ces08, ces11, ces15phone, ces15web, ces19phone, ces19web, ces21)
ces.list %>%
  map(., nrow)
#Provide names for list
names(ces.list)<-c(1965, 1968, 1972, 1974, 1979, 1980, 1984, 1988, 1993, 1997, 2000, 2004, 2006, 2008, 2011, "2015 Phone","2015 Web", "2019 Phone","2019 Web", 2021)
#Common variables to be selected
#common_vars<-c('male')
common_vars<-c('male',
               'union_both',
               'region', 'union',
               'degree',
               'quebec',
               'age',
               'religion',
               'vote',
               'income',
               'turnout', 'mip',
               'personal_retrospective', 'efficacy_external', 'efficacy_external2', 'efficacy_internal', 'political_efficacy',
               'foreign', 'non_charter_language', 'language', 'income2', 'mode', 'election', 'previous_vote', 'sector', 'size',
               'ideology', 'women',
               'redistribution',
               'market_liberalism',
               'immigration_rates',
               'traditionalism',
               'traditionalism2',
               'trad1', 'trad2',
               'market1','market2', 'education','national_retrospective', 'vote3', 'postgrad',
               'enviro', 'race', 'welfare', 'quebec_sov', 'quebec_accom', 'pol_interest', 'satdem', 'satdem2',
               'household', 'income_house', 'previous_vote3', 'promise', 'trust', 'duty',
               'enviro_spend', 'efficacy_rich', 'prov', 'income_tertile', 'vote10', 'previous_vote3', 'unemployed',
               'party_id', 'party_id2', 'party_close', 'party_id3', 'occupation', 'occupation3',
               'manage_economy', 'manage_environment', 'manage_immigration', 'address_issue', 'immigration_job',
               'liberal_leader', 'conservative_leader', 'ndp_leader', 'bloc_leader', 'green_leader', 'ppc_leader',
               'inequality_increase', 'business', 'business_tax', 'employment', 'homeowner', 'housing', 'inequality',

               'prov_vote', 'liberal_rating', 'conservative_rating', 'ndp_rating', 'bloc_rating', 'green_rating', 'ppc_rating', 'stay_home', 'feminism_rating')

ces.list %>%
  map(., select, any_of(common_vars))%>%
  #bind_rows smushes all the data frames together, and creates a variable called election
  bind_rows()->ces
#show what we have.
glimpse(ces)
#> Rows: 120,719
#> Columns: 54
#> $ male                   <dbl+lbl> 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0…
#> $ occupation             <dbl+lbl>  5,  5,  5,  5,  5,  5,  1, NA,  2,  5, NA,…
#> $ employment             <dbl+lbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
#> $ union_both             <dbl+lbl> NA,  0,  0, NA, NA, NA,  0, NA,  0, NA, NA,…
#> $ region                 <dbl+lbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
#> $ union                  <dbl+lbl> NA,  0,  0, NA, NA, NA,  0, NA,  0, NA, NA,…
#> $ degree                 <dbl+lbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
#> $ quebec                 <dbl+lbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
#> $ age                    <dbl> 45, 36, 48, 32, 53, 33, 47, 75, 45, 62, 71, 24,…
#> $ religion               <dbl+lbl> 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2…
#> $ vote                   <dbl+lbl>  1,  1,  2,  1,  1,  1,  2,  2,  2,  1,  2,…
#> $ income                 <dbl+lbl>  1,  2,  2,  2,  3,  2,  3,  2,  3,  2,  1,…
#> $ turnout                <dbl+lbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
#> $ mip                    <dbl+lbl> 18,  0, 15, 15, 15,  6, 11, 18, 16, 15, 15,…
#> $ personal_retrospective <dbl> 0.5, 0.0, 0.0, 1.0, 1.0, 0.5, 1.0, 0.5, 1.0, 0.…
#> $ efficacy_external      <dbl> 0, 1, 1, 1, 1, 0, NA, 0, 1, 0, 0, NA, 0, 1, 1, …
#> $ efficacy_external2     <dbl> 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, NA, 0, 0, 1…
#> $ efficacy_internal      <dbl> 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,…
#> $ political_efficacy     <dbl> 0.3333333, 0.6666667, 1.0000000, 0.6666667, 0.3…
#> $ foreign                <dbl+lbl> 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0…
#> $ non_charter_language   <dbl+lbl> 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
#> $ language               <dbl+lbl>  1,  1, NA,  1,  1,  1,  1,  1,  1,  1,  1,…
#> $ party_id               <dbl+lbl> 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1…
#> $ income_tertile         <dbl+lbl>  1,  1,  1,  1,  2,  1,  2,  1,  2,  1,  1,…
#> $ income2                <dbl+lbl>  1,  1,  2,  1,  2,  2,  2,  1,  2,  1,  1,…
#> $ mode                   <chr> "Phone", "Phone", "Phone", "Phone", "Phone", "P…
#> $ election               <dbl> 1965, 1965, 1965, 1965, 1965, 1965, 1965, 1965,…
#> $ sector                 <dbl+lbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ occupation3            <dbl+lbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ ideology               <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ redistribution         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ market_liberalism      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ immigration_rates      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ traditionalism         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ traditionalism2        <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ trad1                  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ trad2                  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ market1                <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ market2                <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ education              <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ national_retrospective <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ vote3                  <dbl+lbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ postgrad               <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ enviro                 <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ pol_interest           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ satdem                 <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ satdem2                <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ household              <dbl+lbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ income_house           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ promise                <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ trust                  <dbl+lbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ enviro_spend           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ inequality             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ efficacy_rich          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
