VARIABLE LABELS
    YEAR           "Année de référence"
    PUMFID         "Identificateur du ménage"
    PERSONID       "Identificateur de la personne"
    FWEIGHT        "Poids final"
    PROV           "Province"
    USZGAP         "Taille ajustée du secteur de résidence"
    MBMREGP        "Région de la Mesure du panier de consommation (MPC)"
    AGEGP          "Groupe d'âge au 31 décembre de l'année de référence"
    SEX            "Sexe"
    MARSTP         "État matrimonial"
    CMPHI          "Indicateur - Études secondaires complétées"
    HLEV2G         "Plus haut niveau de scolarité de la personne, 2e regroupement"
    STUDTFP        "Ind - A fréquenté école, collège, cégep ou univ. pendant année réf"
    FLLPRTP        "Études à temps plein ou à temps partiel pendant année réf"
    FWORKED        "Ind - Personne avait un emploi pendant année réf"
    SCSUM          "Sommaire annuel du temps travaillé pendant année réf"
    ALFST          "Statut d'activité annuel"
    WKSEM          "Nombre de semaines avec emploi pendant année réf"
    WKSUEM         "Nombre de semaines en chômage pendant année réf"
    WKSNLF         "Nombre de semaines hors de la population active pendant année réf"
    USHRWK         "Heures hab. moyennes trav. par semaine à tous emplois pend. année réf"
    ALHRWK         "Total des heures habituellement trav. à tous emplois pendant année réf"
    FPDWK          "Ind - Personne a été employée rémunérée pendant année réf"
    FSEMP          "Ind - Travail autonome pendant année réf"
    IMMST          "Indicateur - Personne est une immigrante reçue"
    YRIMMG         "Nombre d'années depuis l'immigration au Canada, regroupement"
    ALIMO          "Pension alimentaire reçue"
    ALIP           "Pension alimentaire payée"
    ATINC          "Revenu après impôt"
    BURSAR         "Bourses d'études et d'entretien"
    CAPGN          "Gains en capital imposables"
    CCAR           "Frais de garde d'enfants"
    CHBEN          "Prestations pour enfants"
    CHFED          "Total des prestations fédérales pour enfants"
    CHPRV          "Total des prestations provinciales ou territoriales pour enfants"
    COVRET         "Remboursement de prestations fédérales liées à la COVID-19"
    COVTOT         "Prestations liées à la COVID-19"
    CPQPP          "Prestations du RPC/RRQ"
    CQPC           "Cotisations au RPC/RRQ"
    CWB            "Allocation canadienne pour les travailleurs"
    EARNG          "Revenu d'emploi"
    EIBEN          "Prestations d'assurance-emploi"
    EICON          "Contributions à l'assurance-emploi"
    FDITX          "Impôt fédéral"
    FRTXCR         "Crédits d'impôt fédéraux remboursables"
    GI             "Supplément de revenu garanti, Allocation et Allocation au survivant"
    GSTXC          "Crédit TPS/TVH fédéral (exclut crédits pour taxe de vente prov./terr.)"
    GTR            "Transferts gouvernementaux, fédéraux et provinciaux/territoriaux"
    INCTX          "Impôt sur le revenu, fédéral et provincial/territorial"
    INVA           "Revenu de placements"
    MAJRI          "Principale source de revenu"
    MTINC          "Revenu du marché"
    OAS            "Pension de la Sécurité de la vieillesse"
    OASGI          "Total des prestations de Sécurité de la vieillesse"
    OGNIE          "Autres transferts gouvernementaux non inclus ailleurs"
    OGTRAN         "Autres transferts gouvernementaux"
    OTHINC         "Autres revenus"
    OTTXM          "Autres revenus imposables"
    PEN            "Pensions de retraite privées (comprend fractionn. rev. de pension)"
    PENGIV         "Pension fractionnée, montant donné"
    PENREC         "Pension fractionnée, montant perçu"
    PRPEN          "Pensions de retraite privées"
    PRSUPP         "Suppléments provinciaux/territoriaux pour personnes âgées"
    PRTXCR         "Crédits d'impôt remboursables provinciaux/territoriaux"
    PVITX          "Impôt provincial/territorial sur le revenu"
    RPPC           "Cotisations à un régime de pension agréé"
    RSPWI          "Retraits d'un REER"
    SAPIS          "Prestations d'aide sociale"
    SEMP           "Revenu net d'un travail autonome"
    TTINC          "Revenu total avant impôt"
    UDPD           "Cotisations syndicales (et autres primes professionnelles)"
    WGSAL          "Salaires et traitements avant déductions"
    WKRCP          "Indemnités pour accidents du travail"
    EFID           "Identificateur de la famille économique"
    EFSIZE         "Taille de la famille économique"
    EFTYP          "Type de famille économique"
    EFMJIE         "Ind - Soutien économique principal de la famille économique"
    EFMJIEH        "Ind - La famille écon. inclut le soutien écon. princ. du ménage"
    EFRMJIG        "Lien de parenté avec soutien écon. principal de la fam. écon., rgp"
    EFAGOFMP       "Groupe d’âge du membre le plus âgé de la famille économique"
    EFAGYFMP       "Groupe d’âge du membre le plus jeune de la fam. économique"
    EFMJSI         "Principale source de revenu pour la famille économique"
    EFALIMO        "FÉ - Pension alimentaire reçue"
    EFALIP         "FÉ - Pension alimentaire payée"
    EFATINC        "FÉ - Revenu après impôt"
    EFBURSAR       "FÉ - Bourses d'études et d'entretien"
    EFCAPGN        "FÉ - Gains en capital imposables"
    EFCCAR         "FÉ - Frais de garde d'enfants"
    EFCHBEN        "FÉ - Prestations pour enfants"
    EFCHFED        "FÉ - Total des prestations fédérales pour enfants"
    EFCHPRV        "FÉ - Total des prestations provinciales ou territoriales pour enfants"
    EFCOVRET       "FÉ - Remboursement de prestations fédérales liées à la COVID-19"
    EFCOVTOT       "FÉ - Prestations liées à la COVID-19"
    EFCPQPP        "FÉ - Prestations du RPC/RRQ"
    EFCQPC         "FÉ - Cotisations au RPC/RRQ"
    EFCWB          "FÉ - Allocation canadienne pour les travailleurs"
    EFEARNG        "FÉ - Revenu d'emploi"
    EFEIBEN        "FÉ - Prestations d'assurance-emploi"
    EFEICON        "FÉ - Contributions à l'assurance-emploi"
    EFFDITX        "FÉ - Impôt fédéral"
    EFFRTXCR       "FÉ - Crédits d'impôt fédéraux remboursables"
    EFGI           "FÉ - Supplément de revenu garanti, Allocation et Allocation au surv."
    EFGSTXC        "FÉ - Crédit TPS/TVH fédéral (exclut crédits pour taxe vente prov/terr)"
    EFGTR          "FÉ - Transferts gouvernementaux, fédéraux et provinciaux/territoriaux"
    EFINCTX        "FÉ - Impôt sur le revenu, fédéral et provincial/territorial"
    EFINVA         "FÉ - Revenu de placements"
    EFMBIN18       "FÉ - Concept de revenu disponible pour la MPC (base de 2018)"
    EFMTINC        "FÉ - Revenu du marché"
    EFOAS          "FÉ - Pension de la Sécurité de la vieillesse"
    EFOASGI        "FÉ - Total des prestations de Sécurité de la vieillesse"
    EFOGNIE        "FÉ - Autres transferts gouvernementaux non inclus ailleurs"
    EFOGTRAN       "FÉ - Autres transferts gouvernementaux"
    EFOTHINC       "FÉ - Autres revenus"
    EFOTTXM        "FÉ - Autres revenus imposables"
    EFPEN          "FÉ - Pensions de retraite privées (comprend fractionn. rev. pension)"
    EFPENGIV       "FÉ - Déduction pour le montant de pension fractionné"
    EFPENREC       "FÉ - Montant de pension fractionné"
    EFPRPEN        "FÉ - Pensions de retraite privées"
    EFPRSUPP       "FÉ - Suppléments provinciaux/territoriaux pour personnes âgées"
    EFPRTXCR       "FÉ - Crédits d'impôt remboursables provinciaux/territoriaux"
    EFPVITX        "FÉ - Impôt provincial/territorial sur le revenu"
    EFRPPC         "FÉ - Cotisations à un régime de pension agréé"
    EFRSPWI        "FÉ - Retraits d'un REER"
    EFSAPIS        "FÉ - Prestations d'assistance sociale"
    EFSEMP         "FÉ - Revenu net d'un travail autonome"
    EFTTINC        "FÉ - Revenu total avant impôt"
    EFUDPD         "FÉ - Cotisations syndicales (et autres primes professionnelles)"
    EFWGSAL        "FÉ - Salaires et traitements avant déductions"
    EFWKRCP        "FÉ - Indemnités pour accidents du travail"
    CFID           "Identificateur de la famille de recensement"
    CFSIZE         "Taille de la famille de recensement"
    CFCOMP         "Composition de la famille de recensement"
    CFMJIE         "Ind - Soutien économique principal de la famille de recens."
    CFMJIEH        "Ind - La famille de recens. inclut le soutien écon. princ. du ménage"
    CFRMJIG        "Lien de parenté avec soutien écon. principal de la fam. recens., rgp"
    CFAGOFMP       "Groupe d’âge du membre le plus âgé de la fam. de recensement"
    CFAGYFMP       "Groupe d’âge du membre le plus jeune de la fam. de recensement"
    CFMJSI         "Principale source de revenu pour la famille de recensement"
    CFALIMO        "FR - Pension alimentaire reçue"
    CFALIP         "FR - Pension alimentaire payée"
    CFATINC        "FR - Revenu après impôt"
    CFBURSAR       "FR - Bourses d'études et d'entretien"
    CFCAPGN        "FR - Gains en capital imposables"
    CFCCAR         "FR - Frais de garde d'enfants"
    CFCHBEN        "FR - Prestations pour enfants"
    CFCHFED        "FR - Total des prestations fédérales pour enfants"
    CFCHPRV        "FR - Total des prestations provinciales ou territoriales pour enfants"
    CFCOVRET       "FR - Remboursement de prestations fédérales liées à la COVID-19"
    CFCOVTOT       "FR - Prestations liées à la COVID-19"
    CFCPQPP        "FR - Prestations du RPC/RRQ"
    CFCQPC         "FR - Cotisations au RPC/RRQ"
    CFCWB          "FR - Allocation canadienne pour les travailleurs"
    CFEARNG        "FR - Revenu d'emploi"
    CFEIBEN        "FR - Prestations d'assurance-emploi"
    CFEICON        "FR - Contributions à l'assurance-emploi"
    CFFDITX        "FR - Impôt fédéral"
    CFFRTXCR       "FR - Crédits d'impôt fédéraux remboursables"
    CFGI           "FR - Supplément de revenu garanti, Allocation et Allocation au surv."
    CFGSTXC        "FR - Crédit TPS/TVH fédéral (exclut crédits pour taxe vente prov/terr)"
    CFGTR          "FR - Transferts gouvernementaux, fédéraux et provinciaux/territoriaux"
    CFINCTX        "FR - Impôt sur le revenu, fédéral et provincial/territorial"
    CFINVA         "FR - Revenu de placements"
    CFMTINC        "FR - Revenu du marché"
    CFOAS          "FR - Pension de la Sécurité de la vieillesse"
    CFOASGI        "FR - Total des prestations de Sécurité de la vieillesse"
    CFOGNIE        "FR - Autres transferts gouvernementaux non inclus ailleurs"
    CFOGTRAN       "FR - Autres transferts gouvernementaux"
    CFOTHINC       "FR - Autres revenus"
    CFOTTXM        "FR - Autres revenus imposables"
    CFPEN          "FR - Pensions de retraite privées (comprend fractionn. rev. pension)"
    CFPENGIV       "FR - Déduction pour le montant de pension fractionné"
    CFPENREC       "FR - Montant de pension fractionné"
    CFPRPEN        "FR - Pensions de retraite privées"
    CFPRSUPP       "FR - Suppléments provinciaux/territoriaux pour personnes âgées"
    CFPRTXCR       "FR - Crédits d'impôt remboursables provinciaux/territoriaux"
    CFPVITX        "FR - Impôt provincial/territorial sur le revenu"
    CFRPPC         "FR - Cotisations à un régime de pension agréé"
    CFRSPWI        "FR - Retraits d'un REER"
    CFSAPIS        "FR - Prestations d'assistance sociale"
    CFSEMP         "FR - Revenu net d'un travail autonome"
    CFTTINC        "FR - Revenu total avant impôt"
    CFUDPD         "FR - Cotisations syndicales (et autres primes professionnelles)"
    CFWGSAL        "FR - Salaires et traitements avant déductions"
    CFWKRCP        "FR - Indemnités pour accidents du travail"
    HHSIZE         "Taille du ménage"
    HHCOMP         "Composition du ménage"
    HHMJIE         "Ind - Soutien économique principal du ménage"
    LICODA         "Écart relatif - SFR-ApI"
    LICOFA         "Ind - Revenu après impôt sous le SFR-ApI"
    LICODB         "Écart relatif - SFR-AvI"
    LICOFB         "Ind - Revenu avant impôt sous le SFR-AvI"
    LIMSDA         "Écart relatif - MFR-ApI"
    LIMSFA         "Ind - Revenu après impôt sous le seuil de la MFR-ApI"
    MBSCD18        "Écart relatif - MPC (base de 2018)"
    MBSCF18        "Ind - Revenu disponible sous le seuil de la MPC (base de 2018)"
    DWLTYP         "Type de logement"
    DWTENR         "Mode d'occupation du logement"
    REPA           "État du logement"
    SUIT           "Ind - Logement convenable selon la Norme nationale d'occ."
    MORTG          "Ind - Hypothèque sur le logement"
    MORTGM         "Paiement hypothécaire mensuel excluant l'impôt foncier"
    CONDMP         "Frais de condominium mensuels"
    RENTM          "Loyer mensuel payé pour le ménage"
    RNSUB          "Ind - Loyer subventionné par gouvernement, employeur ou parent"
    CHNEED         "Indicateur des besoins impérieux en matière de logement"
    FSCADLTM       "Sécurité alimentaire - situation des adultes (incluant marginale)"
    FSCCHLDM       "Sécurité alimentaire - situation des enfants (incluant marginale)"
    FSCHHLDM       "Sécurité alimentaire - situation du ménage (incluant marginale)"
    VISMINFL       "Indicateur - Statut de minorité visible"
    VERDATE        "Date de création du fichier"
    .
 
