VALUE LABELS
              /AGEGP CFAGOFMP CFAGYFMP EFAGOFMP EFAGYFMP
                 "01"   "0 à 5 ans"
                 "02"   "6 à 9 ans"
                 "03"   "10 à 14 ans"
                 "04"   "15 à 17 ans"
                 "05"   "18 à 24 ans"
                 "06"   "25 à 29 ans"
                 "07"   "30 à 34 ans"
                 "08"   "35 à 39 ans"
                 "09"   "40 à 44 ans"
                 "10"   "45 à 49 ans"
                 "11"   "50 à 54 ans"
                 "12"   "55 à 59 ans"
                 "13"   "60 à 64 ans"
                 "14"   "65 à 69 ans"
                 "15"   "70 ans et plus"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /ALFST
                 "01"   "Occupé(e) toute l'année"
                 "02"   "En chômage toute l'année"
                 "03"   "Inactif(ve) toute l'année"
                 "04"   "Occupé(e) et en chômage pendant l'année"
                 "05"   "Occupé(e) et inactif(ve) pendant l'année"
                 "06"   "En chômage et inactif(ve) pendant l'année"
                 "07"   "Occupé(e), en chômage et inactif(ve) pendant l'année"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /ALHRWK
                 9996   "Enchaînement valide"
                 9997   "Ne sait pas"
                 9998   "Refus"
                 9999   "Non déclaré"
              /ALIMO ALIP ATINC BURSAR CAPGN CCAR CFALIMO CFALIP CFATINC CFBURSAR CFCAPGN CFCCAR CFCHBEN CFCHFED
               CFCHPRV CFCOVRET CFCOVTOT CFCPQPP CFCQPC CFCWB CFEARNG CFEIBEN CFEICON CFFDITX CFFRTXCR CFGI CFGSTXC
               CFGTR CFINCTX CFINVA CFMTINC CFOAS CFOASGI CFOGNIE CFOGTRAN CFOTHINC CFOTTXM CFPEN CFPENGIV CFPENREC
               CFPRPEN CFPRSUPP CFPRTXCR CFPVITX CFRPPC CFRSPWI CFSAPIS CFSEMP CFTTINC CFUDPD CFWGSAL CFWKRCP CHBEN
               CHFED CHPRV COVRET COVTOT CPQPP CQPC CWB EARNG EFALIMO EFALIP EFATINC EFBURSAR EFCAPGN EFCCAR EFCHBEN
               EFCHFED EFCHPRV EFCOVRET EFCOVTOT EFCPQPP EFCQPC EFCWB EFEARNG EFEIBEN EFEICON EFFDITX EFFRTXCR EFGI
               EFGSTXC EFGTR EFINCTX EFINVA EFMBIN18 EFMTINC EFOAS EFOASGI EFOGNIE EFOGTRAN EFOTHINC EFOTTXM EFPEN
               EFPENGIV EFPENREC EFPRPEN EFPRSUPP EFPRTXCR EFPVITX EFRPPC EFRSPWI EFSAPIS EFSEMP EFTTINC EFUDPD EFWGSAL
               EFWKRCP EIBEN EICON FDITX FRTXCR GI GSTXC GTR INCTX INVA MTINC OAS OASGI OGNIE OGTRAN OTHINC OTTXM PEN
               PENGIV PENREC PRPEN PRSUPP PRTXCR PVITX RPPC RSPWI SAPIS SEMP TTINC UDPD WGSAL WKRCP
         999999999996   "Enchaînement valide"
         999999999997   "Ne sait pas"
         999999999998   "Refus"
         999999999999   "Non déclaré"
              /CFCOMP
                 "01"   "Fam. de recens. d’une pers. dans une fam. écon. d’une pers."
                 "02"   "Fam. de recens. d’une pers. ds fam. écon. de plusieurs pers."
                 "03"   "Couple sans enfants"
                 "04"   "Couple avec enfants de 24 ans ou moins"
                 "05"   "Couple avec enfants de 25 ans ou plus seulement"
                 "06"   "Fam. monoparentale (femme) avec enfants de 24 ans ou moins"
                 "07"   "Fam. monoparentale (femme) avec enfants 25 ans ou plus seul."
                 "08"   "Fam. monoparentale (homme) avec enfants de 24 ans ou moins"
                 "09"   "Fam. monoparentale (homme) avec enfants 25 ans ou plus seul."
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /CFMJIE CFMJIEH CMPHI EFMJIE EFMJIEH FPDWK FSEMP FWORKED HHMJIE IMMST LICOFA LICOFB LIMSFA MBSCF18 MORTG
               RNSUB STUDTFP
                  "1"   "Oui"
                  "2"   "Non"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /CFMJSI EFMJSI
                 "01"   "Aucun revenu"
                 "02"   "Salaires et traitements"
                 "03"   "Revenu d'un travail autonome"
                 "04"   "Transferts gouvernementaux"
                 "05"   "Revenu de placements"
                 "06"   "Pensions de retraite"
                 "07"   "Autre revenu"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /CFRMJIG
                  "1"   "Soutien économique principal"
                  "2"   "Conjoint(e)"
                  "3"   "Fils ou fille (ou petit-fils ou petite-fille)"
                  "4"   "Autre"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /CFSIZE EFSIZE HHSIZE
                   96   "Enchaînement valide"
                   97   "Ne sait pas"
                   98   "Refus"
                   99   "Non déclaré"
              /CHNEED
                  "1"   "Ayant des besoins impérieux en matière de logement"
                  "2"   "N'ayant pas des besoins impérieux en matière de logement"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /CONDMP MORTGM RENTM
             99999996   "Enchaînement valide"
             99999997   "Ne sait pas"
             99999998   "Refus"
             99999999   "Non déclaré"
              /DWLTYP
                  "1"   "Maison individuelle"
                  "2"   "Maison double, maison en rangée ou duplex"
                  "3"   "Appartement"
                  "4"   "Autre"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /DWTENR
                  "1"   "Propriété d'un membre du ménage"
                  "2"   "N'appartenant à aucun membre du ménage"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /EFRMJIG
                  "1"   "Soutien économique principal"
                  "2"   "Conjoint(e)"
                  "3"   "Enfant/enfant en tutelle"
                  "4"   "Autre"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /EFTYP
                 "11"   "Homme âgé hors famille économique"
                 "12"   "Femme âgée hors famille économique"
                 "13"   "Homme non âgé hors famille économique"
                 "14"   "Femme non âgée hors famille économique"
                 "21"   "Couple non âgé, sans enfant ou autre parent"
                 "22"   "Couple non âgé, avec enfants"
                 "23"   "Couple non âgé, avec d'autres parents mais sans enfant"
                 "24"   "Couple âgé, sans enfant ou autre parent"
                 "31"   "Famille monoparentale dont le parent est une femme"
                 "32"   "Famille monoparentale dont le parent est un homme"
                 "41"   "Autre type de famille - homme âgé"
                 "42"   "Autre type de famille - femme âgée"
                 "43"   "Autre type de famille - homme non âgé"
                 "44"   "Autre type de famille - femme non âgée"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /FLLPRTP
                  "1"   "Étudiant(e) à temps plein"
                  "2"   "Étudiant(e) à temps partiel"
                  "3"   "Étudiant(e) à la fois à temps plein et à temps partiel"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /FSCADLTM FSCCHLDM FSCHHLDM
                  "0"   "Sécurité alimentaire"
                  "1"   "Insécurité alimentaire marginale"
                  "2"   "Insécurité alimentaire modérée"
                  "3"   "Insécurité alimentaire grave"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /HHCOMP
                  "1"   "Ménage d'une personne"
                  "2"   "Ménage de deux personnes ou plus, une famille économique"
                  "3"   "Ménage de deux personnes ou plus, deux fam. éconon. ou plus"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /HLEV2G
                  "1"   "Niveau inférieur au diplôme d'études secondaires"
                  "2"   "Études secondaires terminées ou postsecondaires partielles"
                  "3"   "Diplôme ou certificat postsecondaire non universitaire"
                  "4"   "Diplôme ou certificat universitaire"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /LICODA LICODB LIMSDA MBSCD18
                999.6   "Enchaînement valide"
                999.7   "Ne sait pas"
                999.8   "Refus"
                999.9   "Non déclaré"
              /MAJRI
                 "01"   "Aucun revenu"
                 "02"   "Salaires et traitements"
                 "03"   "Revenu d'un travail autonome"
                 "04"   "Transferts gouvernementaux"
                 "05"   "Revenu de placements"
                 "06"   "Pensions de retraite privées"
                 "07"   "Autre revenu"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /MARSTP
                 "01"   "Marié(e)"
                 "02"   "Conjoint(e) de fait"
                 "03"   "Séparé(e), divorcé(e) ou veuf(ve)"
                 "04"   "Célibataire (jamais marié(e))"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /MBMREGP
                 "01"   "Terre-Neuve-et-Labrador, rég. rurales et moins de 100 000 h."
                 "02"   "St. John’s, Terre-Neuve-et-Labrador"
                 "03"   "Île-du-Prince-Édouard"
                 "04"   "Nouvelle-Écosse, régions rurales"
                 "05"   "Nouvelle-Écosse, moins de 100 000 habitants et Cape Breton"
                 "06"   "Halifax, Nouvelle-Écosse"
                 "07"   "Nouveau-Brunswick, régions rurales"
                 "08"   "Nouveau-Brunswick, moins de 100 000 habitants et Fredericton"
                 "09"   "Saint John et Moncton, Nouveau-Brunswick"
                 "10"   "Québec, régions rurales"
                 "11"   "Québec, moins de 30 000 habitants"
                 "12"   "Québec, population 30 000 à 99 999"
                 "13"   "Québec, population 100 000 à 499 999"
                 "14"   "Québec, Québec"
                 "15"   "Montréal, Québec"
                 "16"   "Ontario, régions rurales"
                 "17"   "Ontario, moins de 30 000 habitants"
                 "18"   "Ontario, population 30 000 à 99 999"
                 "19"   "Ontario, population 100 000 à 499 999"
                 "20"   "Ontario, population 500 000 et plus"
                 "21"   "Ottawa-Gatineau, partie ontarienne"
                 "22"   "Hamilton/Burlington, Ontario"
                 "23"   "Toronto, Ontario"
                 "24"   "Manitoba, régions rurales"
                 "25"   "Manitoba, moins de 100 000 habitants et Brandon"
                 "26"   "Winnipeg, Manitoba"
                 "27"   "Saskatchewan, rural"
                 "28"   "Saskatchewan, moins de 100 000 habitants"
                 "29"   "Saskatoon, Saskatchewan"
                 "30"   "Regina, Saskatchewan"
                 "31"   "Alberta, régions rurales"
                 "32"   "Alberta, moins de 30 000 habitants"
                 "33"   "Alberta, population 30 000 à 499 999"
                 "34"   "Edmonton, Alberta"
                 "35"   "Calgary, Alberta"
                 "36"   "Colombie-Britannique, régions rurales"
                 "37"   "Colombie-Britannique, moins de 30 000 habitants"
                 "38"   "Colombie-Britannique, population 30 000 à 99 999"
                 "39"   "Colombie-Britannique, population 100 000 à 499 999"
                 "40"   "Vancouver, Colombie-Britannique"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /PROV
                 "10"   "Terre-Neuve-et-Labrador"
                 "11"   "Île-du-Prince Édouard"
                 "12"   "Nouvelle-Écosse"
                 "13"   "Nouveau-Brunswick"
                 "24"   "Québec"
                 "35"   "Ontario"
                 "46"   "Manitoba"
                 "47"   "Saskatchewan"
                 "48"   "Alberta"
                 "59"   "Colombie-Britannique"
                 "60"   "Yukon"
                 "61"   "Territoires du Nord-Ouest"
                 "62"   "Nunavut"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /REPA
                  "1"   "Oui, des réparations majeures sont requises"
                  "2"   "Oui, des réparations mineures sont requises"
                  "3"   "Non, seulement un entretien régulier est requis"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /SCSUM
                 "11"   "Travailleur pour l'année complète à temps plein"
                 "12"   "Travailleur pour l'année complète à temps partiel"
                 "21"   "Travailleur pour une partie de l'année à temps plein"
                 "22"   "Travailleur pour une partie de l'année à temps partiel"
                 "30"   "N'a pas travaillé au cours de l'année"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /SEX
                  "1"   "Homme"
                  "2"   "Femme"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /SUIT
                  "1"   "Convenable"
                  "2"   "Non convenable"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
              /USHRWK
                999.6   "Enchaînement valide"
                999.7   "Ne sait pas"
                999.8   "Refus"
                999.9   "Non déclaré"
              /USZGAP
                 "01"   "Région rurale à l'extérieur des AR et RMR"
                 "02"   "AR, moins de 30 000 habitants"
                 "03"   "AR, 30 000 à 99 999 habitants"
                 "04"   "Région rurale ou AR, moins de 100 000 habitants"
                 "05"   "AR, moins de 100 000 habitants"
                 "06"   "RMR, 100 000 à 499 999 habitants"
                 "07"   "AR, moins de 100 000 hab. ou RMR, 100 000 à 499 999 hab."
                 "08"   "AR, 30 000 à 99 999 hab. ou RMR, 100 0000 à 499 999 hab."
                 "09"   "RMR, 500 000 habitants et plus"
                 "96"   "Enchaînement valide"
                 "97"   "Ne sait pas"
                 "98"   "Refus"
                 "99"   "Non déclaré"
              /VISMINFL
                    1   "Oui"
                    2   "Non"
                    6   "Enchaînement valide"
                    7   "Ne sait pas"
                    8   "Refus"
                    9   "Non déclaré"
              /WKSEM WKSNLF WKSUEM
                   96   "Enchaînement valide"
                   97   "Ne sait pas"
                   98   "Refus"
                   99   "Non déclaré"
              /YRIMMG
                  "1"   "Moins de 10"
                  "2"   "10-19"
                  "3"   "20-29"
                  "4"   "30-39"
                  "5"   "40 et plus"
                  "6"   "Enchaînement valide"
                  "7"   "Ne sait pas"
                  "8"   "Refus"
                  "9"   "Non déclaré"
    .
 
